server:
  port: 6081

spring:
  application:
    name: payment-consumer-feign-6081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka6112:6112/eureka,http://eureka6111:6111/eureka
  instance:
    instance-id: payment-consumer-feign-6081
    prefer-ip-address: true

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

logging:
  level:
    com.hertz.service.PaymentService: debug
