server:
  port: 6003

spring:
  application:
    name: payment-producer-hystrix

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka6112:6112/eureka,http://eureka6111:6111/eureka
  instance:
    instance-id: payment-producer-hystrix-6003
    prefer-ip-address: true